title: "Python workshop - Good practices"
description: "A short description"
remote_theme: just-the-docs/just-the-docs
url: "https://marco-saretta.github.io/python-workshop/"

# Optional but recommended
color_scheme: light
search_enabled: true

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

heading_anchors: true

color_scheme: custom