title: "Python workshop - Good practices"
description: "A short description"
remote_theme: just-the-docs/just-the-docs
url: "https://marco-saretta.github.io/python-workshop/"
markdown: kramdown        # <-- add this line
color_scheme: nil
search_enabled: true

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
    